## LIBRERIA

In [4]:
from sqlalchemy import create_engine
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import mapclassify 
import matplotlib.patheffects as pe
from matplotlib.lines import Line2D

## 1.CONEXIÓN BASE DE DATOS

In [5]:
DB_HOST = 'localhost'
DB_PORT = 5432
DB_NAME = 'CensoRM2017'
DB_USER = 'postgres'
DB_PASSWORD = 'postgres' 

engine = create_engine(
    f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

## 2.CARGAR DATOS

In [6]:
sql_comunas = '''
SELECT nom_comuna, geom
FROM dpa.comunas_rm_shp;
'''

gdf_comunas    = gpd.read_postgis(sql_comunas, engine, geom_col='geom')
gdf_centroides = gdf_comunas.copy()
gdf_centroides['geometry'] = gdf_comunas.centroid

print(f'Comunas: {len(gdf_comunas)}')
display(gdf_comunas)

Comunas: 52

             nom_comuna                                               geom
0              LO PRADO  MULTIPOLYGON (((339891.406 6298725.5, 339967.9...
1         INDEPENDENCIA  MULTIPOLYGON (((345568.713 6303028.6, 345794.7...
2             LO ESPEJO  MULTIPOLYGON (((344800.111 6290835.676, 343521...
3             SAN RAMÓN  MULTIPOLYGON (((348001.245 6290000.561, 348259...
4           LA CISTERNA  MULTIPOLYGON (((346490 6286649.498, 345256.375...
5   PEDRO AGUIRRE CERDA  MULTIPOLYGON (((344800.111 6290835.676, 342530...
6            SAN MIGUEL  MULTIPOLYGON (((348011.801 6290001.611, 348001...
7              CONCHALÍ  MULTIPOLYGON (((342803.041 6306876.533, 343470...
8           SAN JOAQUÍN  MULTIPOLYGON (((349191.057 6294882.314, 349437...
9             LA GRANJA  MULTIPOLYGON (((350573.769 6287953.638, 350492...
10                MACUL  MULTIPOLYGON (((353151.246 6293305.479, 352541...
11            EL BOSQUE  MULTIPOLYGON (((346490 6286649.498, 346375.281...
12          PROVIDENCIA  MULTIPOLYGON (((350513.889 6301429.624, 351087...
13          CERRO NAVIA  MULTIPOLYGON (((340453.5 6301374.5, 339967.938...
14        QUINTA NORMAL  MULTIPOLYGON (((341478.156 6302197.5, 342445.8...
15                ÑUÑOA  MULTIPOLYGON (((353737.653 6299021.183, 354002...
16             RECOLETA  MULTIPOLYGON (((349345.743 6303502.526, 349557...
17     ESTACIÓN CENTRAL  MULTIPOLYGON (((343946.339 6297483.001, 344050...
18            CERRILLOS  MULTIPOLYGON (((340891.156 6294050.5, 340985.7...
19             LA REINA  MULTIPOLYGON (((357053.171 6299607.003, 358417...
20             SANTIAGO  MULTIPOLYGON (((345708.841 6299803.857, 346456...
21             VITACURA  MULTIPOLYGON (((353733.156 6308194.044, 354188...
22           LA PINTANA  MULTIPOLYGON (((348583.682 6285649.317, 348623...
23                RENCA  MULTIPOLYGON (((342902.46 6304068.741, 343591....
24           HUECHURABA  MULTIPOLYGON (((345243.136 6310974.444, 345664...
25            QUILICURA  MULTIPOLYGON (((342700.812 6311464.532, 342755...
26            PEÑALOLÉN  MULTIPOLYGON (((355872.969 6296346.5, 356482.0...
27             PEÑAFLOR  MULTIPOLYGON (((328389.396 6283192.192, 328260...
28      CALERA DE TANGO  MULTIPOLYGON (((335806.372 6283957.394, 335820...
29           LA FLORIDA  MULTIPOLYGON (((364837.485 6292856.894, 365166...
30          PUENTE ALTO  MULTIPOLYGON (((360392.705 6287195.362, 360655...
31             EL MONTE  MULTIPOLYGON (((315609.88 6278604.768, 315972....
32        PADRE HURTADO  MULTIPOLYGON (((322908.431 6290469.447, 323169...
33           LAS CONDES  MULTIPOLYGON (((362514.045 6307343.764, 362547...
34                MAIPÚ  MULTIPOLYGON (((334985.558 6296509.318, 335895...
35            TALAGANTE  MULTIPOLYGON (((328536.245 6276673.169, 327497...
36             PUDAHUEL  MULTIPOLYGON (((334841.581 6306090.591, 335918...
37        ISLA DE MAIPO  MULTIPOLYGON (((328334.74 6268185.173, 328693....
38         SAN BERNARDO  MULTIPOLYGON (((342829.757 6285775.853, 342605...
39                 BUIN  MULTIPOLYGON (((348370.676 6275014.006, 347922...
40               PIRQUE  MULTIPOLYGON (((366012.494 6282675.351, 366416...
41                LAMPA  MULTIPOLYGON (((332923.346 6328108.491, 333740...
42          MARÍA PINTO  MULTIPOLYGON (((289457.401 6300880.567, 290116...
43               TILTIL  MULTIPOLYGON (((338145.621 6355646.177, 339017...
44         LO BARNECHEA  MULTIPOLYGON (((376906.752 6335992.693, 377122...
45             CURACAVÍ  MULTIPOLYGON (((313644.401 6324197.522, 313672...
46                ALHUÉ  MULTIPOLYGON (((314541.448 6247991.222, 315279...
47            SAN PEDRO  MULTIPOLYGON (((265756.062 6260577.181, 266149...
48                PAINE  MULTIPOLYGON (((350491.702 6265654.977, 350552...
49               COLINA  MULTIPOLYGON (((350664.829 6352777.501, 351253...
50            MELIPILLA  MULTIPOLYGON (((315102.551 6286932.333, 315330...
51    SAN JOSÉ DE MAIPO  MULTIPOLYGON (((398800.368 6341705.962, 399178...

## 3.INDICADORES

In [7]:
sql_indicadores = '''
WITH agg AS 
(
SELECT c.nom_comuna, 
z.geocodigo::DOUBLE PRECISION AS geocodigo, 
ROUND (((COUNT(*) FILTER (WHERE UPPER(p.p18) IN ('A', 'B')))*100.0/COUNT(*)),2) AS sector_primario,
ROUND (((COUNT(*) FILTER (WHERE p.p15 = 12))*100.0/COUNT(*)),2) AS porcentaje_profesionales
FROM public.personas AS p
JOIN public.hogares AS h
ON p.hogar_ref_id = h.hogar_ref_id
JOIN public.viviendas AS v
ON h.vivienda_ref_id = v.vivienda_ref_id
JOIN public.zonas AS z
ON v.zonaloc_ref_id = z.zonaloc_ref_id
JOIN public.comunas AS c
ON z.codigo_comuna = c.codigo_comuna
JOIN public.provincias AS pr 
ON pr.provincia_ref_id = c.provincia_ref_id
WHERE pr.nom_provincia = 'MELIPILLA'
GROUP BY c.nom_comuna, z.geocodigo
)
SELECT a.*, shp.geom
FROM agg AS a
JOIN dpa.zonas_censales_rm AS shp
ON shp.geocodigo = a.geocodigo;
'''

In [8]:
gdf = gpd.read_postgis(sql_indicadores, engine, geom_col='geom')

In [9]:
gdf

,nom_comuna,geocodigo,sector_primario,porcentaje_profesionales,geom
0,ALHUÉ,1.350201e+10,18.37,9.35,"MULTIPOLYGON (((306250.709 6232826.305, 306344..."
1,ALHUÉ,1.350201e+10,14.58,0.00,"MULTIPOLYGON (((304044.672 6232382.536, 304070..."
2,ALHUÉ,1.350202e+10,34.98,3.67,"MULTIPOLYGON (((295472.326 6234041.035, 295780..."
3,ALHUÉ,1.350202e+10,45.07,14.08,"MULTIPOLYGON (((291374.242 6233598.206, 291459..."
4,ALHUÉ,1.350203e+10,16.65,5.22,"MULTIPOLYGON (((311500.554 6233729.707, 311534..."
...,...,...,...,...,...
219,SAN PEDRO,1.350506e+10,19.27,6.42,"MULTIPOLYGON (((270726.55 6239669.063, 270758...."
220,SAN PEDRO,1.350506e+10,17.96,5.83,"MULTIPOLYGON (((263857.95 6238016.555, 264500...."
221,SAN PEDRO,1.350506e+10,19.80,2.48,"MULTIPOLYGON (((266072.646 6242106.632, 266163..."
222,SAN PEDRO,1.350506e+10,20.69,1.38,"MULTIPOLYGON (((263628.433 6239389.385, 263669..."
223,SAN PEDRO,1.350506e+10,0.00,0.00,"MULTIPOLYGON (((260779.116 6231803.862, 261208..."

In [10]:
gdf[['sector_primario','porcentaje_profesionales']].describe().round(2)

       sector_primario  porcentaje_profesionales
count           224.00                    224.00
mean             13.69                      9.19
std               9.49                      7.50
min               0.00                      0.00
25%               6.49                      4.40
50%              12.50                      7.09
75%              18.39                     11.34
max              75.00                     41.10